### ISSUE TITLE
Updates on your configs for this repo?

### ISSUE THREAD

**Issue by hungry-bogart** [ChristianLempa/homelab#1]
I know you are extremely busy, but I was just curious if you plan on updating this repo with your configs. It would be nice to see them. Great videos all around. Thanks for all your contributions to the homelab community.

**Comment by ChristianLempa** [comment]
That is at least the plan. I'm not sure when exactly I'm going to publish it, but I will let you know on YouTube. Give me a few weeks, you need to be patient with me ;)
